name = "NYMinecraft"
author = "Vthunknown"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf6fb347cf3225b28aa7acc9f4a53ca0bf223d8f799d207a588f02f2b19c3bc0"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
