name = "NYMinecraft"
author = "Vthunknown"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbcbbc2800ee220ceb73b465fb57ef043a2d73547a39db7a93fb099074328643"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
