name = "NYMinecraft"
author = "Vthunknown"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbe885902ecbd1c562114320e61dcb98192e2f60c4b12449f2bd55d818c115d2"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
